name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9.3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_surat
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, bcmath, pdo, pdo_mysql
        coverage: none

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.15.0'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install PHP Dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Install JS Dependencies
      run: npm ci

    - name: Build Frontend Assets (Vite)
      run: npm run build

    - name: Generate Key
      run: php artisan key:generate

    - name: Set Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Wait for MySQL
      run: sleep 15

    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: db_surat
        DB_USERNAME: root
        DB_PASSWORD: ""
      run: php artisan migrate --force

    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: db_surat
        DB_USERNAME: root
        DB_PASSWORD: ""
      run: php artisan test
